name: your_env_name
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py39h06a4308_0
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==2.2.2
    - accelerate==1.5.2
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.14
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - attrs==25.3.0
    - bert-score==0.3.13
    - bitsandbytes==0.44.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cmake==3.31.6
    - contourpy==1.3.0
    - cycler==0.12.1
    - datasets==3.4.1
    - deepspeed==0.15.4
    - dill==0.3.8
    - einops==0.8.1
    - evaluate==0.4.3
    - filelock==3.18.0
    - flatbuffers==25.2.10
    - fonttools==4.57.0
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.71.0
    - h5py==3.13.0
    - hjson==3.1.0
    - huggingface-hub==0.29.3
    - idna==3.10
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - jinja2==3.1.6
    - joblib==1.4.2
    - keras==3.9.2
    - kiwisolver==1.4.7
    - libclang==18.1.1
    - lit==18.1.8
    - markdown==3.8
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - mdurl==0.1.2
    - ml-dtypes==0.5.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.2.0
    - multiprocess==0.70.16
    - namex==0.0.8
    - networkx==3.2.1
    - ninja==1.11.1.4
    - nltk==3.9.1
    - numpy==1.26.4
    - nvidia-ml-py==12.570.86
    - opt-einsum==3.4.0
    - optree==0.15.0
    - packaging==24.2
    - pandas==2.2.3
    - peft==0.15.0
    - pillow==11.1.0
    - propcache==0.3.1
    - protobuf==5.29.4
    - psutil==7.0.0
    - py-cpuinfo==9.0.0
    - pyarrow==19.0.1
    - pydantic==2.11.1
    - pydantic-core==2.33.0
    - pygments==2.19.1
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==14.0.0
    - rouge-score==0.1.2
    - safetensors==0.5.3
    - sentencepiece==0.2.0
    - six==1.17.0
    - sympy==1.13.3
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.19.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==3.0.1
    - tf-keras==2.19.0
    - tokenizers==0.20.3
    - torch==2.0.0+cu118
    - torchaudio==2.0.1+cu118
    - torchvision==0.15.1+cu118
    - tqdm==4.67.1
    - transformers==4.45.2
    - triton==2.0.0
    - typing-extensions==4.13.0
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==2.3.0
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - xxhash==3.5.0
    - yarl==1.18.3
    - zipp==3.21.0
